MySaleDDD/Controllers/BrandController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MySaleDDD.Core;
using MySaleDDD.Core.Models;
using MySaleDDD.Data.Repository;
using MySaleDDD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySaleDDD.Controllers
{
    public class BrandController : BaseController
    {
        //private readonly IBrandRepository _repo;   //Dont Use Generic Repository
        private readonly IGenericRepository<Brand> _repo;
        private readonly IMapper _mapper;
        public BrandController(IGenericRepository<Brand> repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Brand> brands = await _repo.GetAllAysnc();
            IEnumerable<BaseViewModel> brandViewModels = _mapper.Map<IEnumerable<Brand>, IEnumerable<BaseViewModel>>(brands);
            return View(brandViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new BaseViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(BaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Brand brand = _mapper.Map<BaseViewModel, Brand>(model);
               var result= await _repo.InsertAsync(brand);
                if (result == -1)
                    ErrorMessage = Resources.Messages.Error;
                SuccessMessage = Resources.Messages.ChangesSavedSuccessfully;
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            Brand brand = await _repo.GetByIdAsync(Id);
            if (brand == null) return NotFound();
            BaseViewModel model = _mapper.Map<Brand, BaseViewModel>(brand);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(BaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Brand brand = _mapper.Map<BaseViewModel, Brand>(model);
                var result= await  _repo.UpdateAsync(brand);
                if (result == -1)
                    ErrorMessage = "خطا در ویرایش اطلاعات";
                SuccessMessage = "اطلاعات با موفقیت ویرایش شد";
                return RedirectToAction("Edit",new { Id=model.Id});
            }


            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var result= await _repo.RemoveAsync(Id);
            if (result <1)
                ErrorMessage = "خطا در حذف اطلاعات";
            SuccessMessage = "اطلاعات با موفقیت حذف شد";
            return RedirectToAction("Index");
        }
    }
}

MySaleDDD/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MySaleDDD.Core.Models;
using MySaleDDD.Data.Repository;
using MySaleDDD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySaleDDD.Controllers
{
    public class OrderController : BaseController
    {
        readonly IGenericRepository<Order> _repo;
        readonly IGenericRepository<Product> _repoProduct;
        IMapper _mapper;

        public OrderController(IGenericRepository<Order> repo,
            IGenericRepository<Product> repoProduct, IMapper mapper)
        {
            _repo = repo;
            _repoProduct = repoProduct;
            _mapper = mapper;
        }
        //[Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            IQueryable<Order> list = _repo.GetASQueryable("Product");
            if (User.IsInRole("Customer"))
            {
                list = list.Where(woak => woak.SystemUserId == UserId);
            }

            IEnumerable<OrderViewModel> result = _mapper.Map<IEnumerable<Order>, IEnumerable<OrderViewModel>>(list);

            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            FillDropDown();
            return View(new OrderViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderViewModel model)
        {
            model.SystemUserId = UserId;

            if (ModelState.IsValid)
            {
                Order item = _mapper.Map<OrderViewModel, Order>(model);
                item.Confirm = true;
                await _repo.InsertAsync(item);

                SuccessMessage = Resources.Messages.ChangesSavedSuccessfully;

                return RedirectToAction("Edit", new { id = item.Id });
            }
            ErrorMessage = Resources.Messages.RequiredField;
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            FillDropDown();
            var model = await _repo.GetByIdAsync(id);

            OrderViewModel result = _mapper.Map<Order, OrderViewModel>(model);

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(OrderViewModel model)
        {
            model.SystemUserId = UserId;

            if (ModelState.IsValid)
            {
                Order item = _mapper.Map<OrderViewModel, Order>(model);
                item.Confirm = true;
                var result = await _repo.UpdateAsync(item);
                SuccessMessage = Resources.Messages.ChangesSavedSuccessfully;

                return RedirectToAction("Edit", new { id = item.Id });
            }
            ErrorMessage = Resources.Messages.RequiredField;
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _repo.RemoveAsync(id);
            if (result < 1)
            {
                if (TempData["Error"] != null)
                    TempData.Remove("Error");

                TempData.Add("Error", Resources.Messages.ProblemDeletingItem);
            }
            return RedirectToAction("Index");
        }
        private void FillDropDown()
        {
            ViewBag.Products = _repoProduct.GetAll().Select(x => new SelectListItem
            {
                Text = x.Titel,
                Value = x.Id.ToString()
            }).ToList();
        }
    }
}

MySaleDDD/Controllers/UnitController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MySaleDDD.Core.Models;
using MySaleDDD.Data.Repository;
using MySaleDDD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySaleDDD.Controllers
{
    public class UnitController : BaseController
    {
        //private readonly IBrandRepository _repo;   //Dont Use Generic Repository
        private readonly IGenericRepository<Unit> _repo;
        private readonly IMapper _mapper;
        public UnitController(IGenericRepository<Unit> repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Unit> units = await _repo.GetAllAysnc();
            IEnumerable<BaseViewModel> UnitViewModels = _mapper.Map<IEnumerable<Unit>, IEnumerable<BaseViewModel>>(units);
            return View(UnitViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new BaseViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(BaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Unit unit = _mapper.Map<BaseViewModel, Unit>(model);
                var result = await _repo.InsertAsync(unit);
                if (result == -1)
                    ErrorMessage = Resources.Messages.Error;
                SuccessMessage = Resources.Messages.ChangesSavedSuccessfully;
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            Unit unit = await _repo.GetByIdAsync(Id);
            if (unit == null) return NotFound();
            BaseViewModel model = _mapper.Map<Unit, BaseViewModel>(unit);
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(BaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Unit unit = _mapper.Map<BaseViewModel, Unit>(model);
                var result = await _repo.UpdateAsync(unit);
                if (result == -1)
                    ErrorMessage = "خطا در ویرایش اطلاعات";
                SuccessMessage = "اطلاعات با موفقیت ویرایش شد";
                return RedirectToAction("Edit", new { Id = model.Id });
            }


            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var result = await _repo.RemoveAsync(Id);
            if (result < 1)
                ErrorMessage = "خطا در حذف اطلاعات";
            SuccessMessage = "اطلاعات با موفقیت حذف شد";
            return RedirectToAction("Index");
        }
    }
}

MySaleDDD/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MySaleDDD.Core.Models;
using MySaleDDD.Helper;
using MySaleDDD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MySaleDDD.Controllers
{
    public class UserController : BaseController
    {
        private IMapper _mapper;

        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager,
            SignInManager<ApplicationUser> signInManager, IMapper mapper)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var model = _userManager.Users.Select(x => new UserViewModel  //نحوه مپ کردن مانند قبلی ها تیست چون از ریپازیتوری نمی گیریم و از یوزرمنیجر می گیریم  
            {
                FirstName = x.FirstName,
                LastName = x.LastName,
                Mobile = x.Mobile,
                UserName = x.UserName,
                Id = x.Id
            });
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            //کلیمز هایی رو که نوشتیم رو لیستش(لیست فرم ها) رو می دیم به ویوبگ زیر
            ViewBag.Claims = typeof(AccessClaims).GetFields().Select(x => new KeyValueViewModel
            {
                Key =
                x.Name,
                Value = x.GetValue(new AccessClaims()).ToString()
            }).ToList(); //name=key , value=Display Read From AccessClaims Class
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (model.Password == null)
                return View(model);
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.UserName,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber,
                    EmailConfirmed = true,
                    PhoneNumberConfirmed = true,
                    Mobile = model.Mobile,
                    AddDate = DateTime.Now
                };
                var result = await _userManager.CreateAsync(user, model.Password); //Create User

                //Save Roles and Claimes 
                if (result.Succeeded)
                {
                    if (await _roleManager.FindByNameAsync(model.RoleType.ToString()) == null)
                    {
                        await _roleManager.CreateAsync(new ApplicationRole
                        {
                            Name = model.RoleType.ToString(),
                            NormalizedName = model.RoleType.ToString().ToUpper()  //User.IsInRole("Admin") ادمین بزرگ یا کوچک حساس نمی شود
                        });
                    }
                    await _userManager.AddToRoleAsync(user, model.RoleType.ToString()); // نقش کاربر را تخصیص می دهیم
                    if (model.Claims.Count > 0) //اگر فرمی تخصیص داده شده است?
                    {
                        var claims = model.Claims.Select(x => new Claim(nameof(AccessClaims), x));// نام کلیمز رو اختصاص میده و نه دیسپلیی که برایش تعیین کردیم را
                        await _userManager.AddClaimsAsync(user, claims);
                    }
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
            ViewBag.Claims = typeof(AccessClaims).GetFields().Select(x => new KeyValueViewModel
            {
                Key = x.Name,
                Value = x.GetValue(new AccessClaims()).ToString()
            }).ToList();
            var item = await _userManager.FindByIdAsync(Id);
            if (item != null)
            {
                var model = _mapper.Map<ApplicationUser, UserViewModel>(item);
                var roles = await _userManager.GetRolesAsync(item);
                if (roles.Any()) //اگر رولی وجود داشت
                    model.RoleType = Enum.Parse<RoleType>(roles.FirstOrDefault()); // نوع رول رو پر می کنیم
                //فرم هایی که دسترسی داشته رو می کشیم بیرون و در لیست استرینگ ها قرار بدیم و پاس بدیم بره 
                // باید از کلیمز ها بخوانیم
                model.Claims = (await _userManager.GetClaimsAsync(item)).Where(x => x.Type == nameof(AccessClaims)).Select(x => x.Value).ToList();
                return View(model);
            }
            return RedirectToAction("Index");

        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (model.Password == null)
                return View(model);
            if (ModelState.IsValid)
            {
                var userFounded = await _userManager.FindByIdAsync(model.Id);
                if (userFounded != null)
                {
                    userFounded.UserName = model.UserName;
                    userFounded.FirstName = model.FirstName;
                    userFounded.LastName = model.LastName;
                    userFounded.Email = model.Email;
                    userFounded.PhoneNumber = model.PhoneNumber;
                    userFounded.EmailConfirmed = true;
                    userFounded.PhoneNumberConfirmed = true;
                    userFounded.Mobile = model.Mobile;
                    userFounded.LastModified = DateTime.Now;
                };

                if (!string.IsNullOrEmpty(model.Password))
                {
                    var token = await _userManager.GeneratePasswordResetTokenAsync(userFounded);
                    await _userManager.ResetPasswordAsync(userFounded, token, model.Password);
                }
                await _userManager.UpdateAsync(userFounded);
                //می خواهیم رول های کابر را اپدیت کنیم
                var user = await _userManager.FindByIdAsync(model.Id);  //چون اپدیت شده است از اول پیدا می کنیم
                var roles = await _userManager.GetRolesAsync(user);
                // اول رول های قبلی را پاک می کنیم
                await _userManager.RemoveFromRolesAsync(user, roles);
                if (await _roleManager.FindByNameAsync(model.RoleType.ToString()) == null)
                {
                    await _roleManager.CreateAsync(new ApplicationRole
                    {
                        Name = model.RoleType.ToString().ToUpper(),
                        NormalizedName = model.RoleType.ToString().ToUpper()  //User.IsInRole("Admin") ادمین بزرگ یا کوچک حساس نمی شود
                    });
                }
                //رول های جدید را می زنیم
                await _userManager.AddToRoleAsync(user, model.RoleType.ToString());
                await _userManager.RemoveClaimsAsync(user, (await _userManager.GetClaimsAsync(user)));

                if (model.Claims.Count > 0) //اگر فرمی تخصیص داده شده است?
                {
                    var claims = model.Claims.Select(x => new Claim(nameof(AccessClaims), x));// نام کلیمز رو اختصاص میده و نه دیسپلیی که برایش تعیین کردیم را
                    await _userManager.AddClaimsAsync(user, claims);
                }
                SuccessMessage = Resources.Messages.ChangesSavedSuccessfully;
                return RedirectToAction("Edit", new { Id = userFounded.Id });
            }
            ErrorMessage = "اطلاعات کاربر جاری نامعتبر است";
            return View(model);
        }
    }
}

MySaleDDD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalesDDD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/fontawesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/brands.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/solid.css" rel="stylesheet" />
    <link href="~/lib/searchable-option-list-master/sol.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">فروش لپ تاپ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                        </li>
                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">اطلاعات پایه</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-controller="Unit" asp-action="Index">واحد</a>

                                <a class="dropdown-item" asp-controller="Brand" asp-action="Index">برند</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Product" asp-action="Index">محصولات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="User" asp-action="Index">کاربران</a>
                        </li>


                    </ul>

                </div>
            </div>
            <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Order" asp-action="Index">
                <span id="cardSpan"></span>&nbsp;<i class="fa fa-shopping-basket"></i>

            </a>
            @using (Html.BeginForm("Logout", "Account", method: FormMethod.Post, new { @class = "form-inline my-2 my-lg-0" }))
            {
                @Html.AntiForgeryToken()
                <button style="background: none;border:none;" type="submit" class="btn btn-outline-success my-2 my-sm-2 text-white" id="btnLogout"><i class="fa fa-power-off"></i>خروج</button>
            }
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/searchable-option-list-master/sol.js"></script>
    <script>
        $(function () {
            $('select:not(.not-sol)').searchableOptionList({
                texts: {
                    notItemAvailable: 'موردی یافت نشد',
                    selectAll: 'همه',
                    selectNone: 'هیچکدام',
                    searchplaceholder: 'برای انتخاب جستجو کنید'
                }
            })
        })
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MySaleDDD/Views/Shared/_Messages.cshtml
@if (TempData["ErrorMessages"] != null)
{
    <div class=" alert alert-danger" role="alert">
        @TempData["ErrorMessages"]
    </div>
}
@if (TempData["SuccessMessage"] != null)
{
    <div class=" alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}